### ISSUE TITLE
Indentation of labels in scoping heirachy

### ISSUE THREAD

**Issue by mrspeaker** [mweidhagen/kickasm-mode#1]
Hey, thanks for the awesome mode, I've been using it a lot and it's fantastc.

I was wondering - is there away to indent labels according to their [scoping hierarchy](http://www.theweb.dk/KickAssembler/webhelp/content/ch09s03.html)? I was trying to follow along with some code from this [c64 series](https://youtu.be/z7z4aM6mLmI?t=5057) but it seems like curly braces are pretty much ignored - and all labels appear at the same indent level.

Are scopes unsupported or am I missing a customization? 

Thanks again for your work.

**Comment by mweidhagen** [comment]
Hi, I'm glad you like it!

I never thought about label scoping when I designed it, so labels are always put at the start of a line. There is currently no customization that will help.

I will have a look at it and if it is not too complicated I will implement a customization to enable it. It might take a while though.

**Comment by mweidhagen** [comment]
I have added this now but it is disabled by default. Enable it through customization: kickasm-indent-labels-to-scoping-level. I also added two other variables that is useful to customize: kickasm-scoping-indent, kickasm-scoping-label-indent.
