### ISSUE TITLE
Kickasm-mode breaks grep?

### ISSUE THREAD

**Issue by mrspeaker** [mweidhagen/kickasm-mode#2]
If I start `kickasm-mode` on any file, the next time I try to do an `rgrep` (anywhere in emacs), the grep results are not clickable - and the display is a bit corrupted.

 Running `rgrep` before starting `kickasm-mode` on any files:
<img width="393" alt="pre-kick" src="https://user-images.githubusercontent.com/129330/102156890-85e8df80-3e4c-11eb-83a4-f7cf0501f913.png">
Running `rgrep` after starting `kickasm-mode`:
<img width="387" alt="post-kick" src="https://user-images.githubusercontent.com/129330/102156964-a5800800-3e4c-11eb-98c4-1467f58ab7b1.png">

This seems like it really probably isn't kickasm-mode's fault - and is likely something with my setup -  but I've done as much digging as I can and I'm stuck. If it doesn't sound like it's logical then please feel free to close this issue, but if you have any ideas I'd appreciate it, because it means I need to close all asm files and restart emacs to fix it.

**Comment by mrspeaker** [comment]
I tried "bisecting" the code and found something in `kickasm-compilation-setup-function` when setting `(setq-local compilation-error-regexp-alist kickasm-error-regexp-alist)`. This is causing issues with my `compilation-error-regexp-alist` list - and everywhere, not just in kickasm-mode.

The regex list looked more like values that were in `compilation-error-regexp-alist-alist` (rather than `compilation-error-regexp-alist`) so I tried changing the line to `(setq-local compilation-error-regexp-alist-alist kickasm-error-regexp-alist)`. Everything *appears* to be working correctly now: Compiles, shows correct error locations, and doesn't break grep... though, I have no idea if it's actually correct!

**Comment by mweidhagen** [comment]
Thanks for debugging it for me :-)
I had copied that part from octave mode so I guess that is bugged as well. It looked a bit weird and "hacky", so I have looked at a couple of other compilation modes instead where it looks more correct and used that. I have tried with rgrep and it works fine for me now at least.
